// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: redirector.proto

/*
Package redirectorpb is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package redirectorpb

import (
	"context"
	"errors"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var (
	_ codes.Code
	_ io.Reader
	_ status.Status
	_ = errors.New
	_ = runtime.String
	_ = utilities.NewDoubleArray
	_ = metadata.Join
)

func request_Redirector_RedirectURL_0(ctx context.Context, marshaler runtime.Marshaler, client RedirectorClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq RedirectRequest
		metadata runtime.ServerMetadata
		err      error
	)
	if req.Body != nil {
		_, _ = io.Copy(io.Discard, req.Body)
	}
	val, ok := pathParams["short_url"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "short_url")
	}
	protoReq.ShortUrl, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "short_url", err)
	}
	msg, err := client.RedirectURL(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err
}

func local_request_Redirector_RedirectURL_0(ctx context.Context, marshaler runtime.Marshaler, server RedirectorServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var (
		protoReq RedirectRequest
		metadata runtime.ServerMetadata
		err      error
	)
	val, ok := pathParams["short_url"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "short_url")
	}
	protoReq.ShortUrl, err = runtime.String(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "short_url", err)
	}
	msg, err := server.RedirectURL(ctx, &protoReq)
	return msg, metadata, err
}

// RegisterRedirectorHandlerServer registers the http handlers for service Redirector to "mux".
// UnaryRPC     :call RedirectorServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterRedirectorHandlerFromEndpoint instead.
// GRPC interceptors will not work for this type of registration. To use interceptors, you must use the "runtime.WithMiddlewares" option in the "runtime.NewServeMux" call.
func RegisterRedirectorHandlerServer(ctx context.Context, mux *runtime.ServeMux, server RedirectorServer) error {
	mux.Handle(http.MethodGet, pattern_Redirector_RedirectURL_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/redirectorpb.Redirector/RedirectURL", runtime.WithHTTPPathPattern("/{short_url}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_Redirector_RedirectURL_0(annotatedContext, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_Redirector_RedirectURL_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})

	return nil
}

// RegisterRedirectorHandlerFromEndpoint is same as RegisterRedirectorHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterRedirectorHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.NewClient(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()
	return RegisterRedirectorHandler(ctx, mux, conn)
}

// RegisterRedirectorHandler registers the http handlers for service Redirector to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterRedirectorHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterRedirectorHandlerClient(ctx, mux, NewRedirectorClient(conn))
}

// RegisterRedirectorHandlerClient registers the http handlers for service Redirector
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "RedirectorClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "RedirectorClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "RedirectorClient" to call the correct interceptors. This client ignores the HTTP middlewares.
func RegisterRedirectorHandlerClient(ctx context.Context, mux *runtime.ServeMux, client RedirectorClient) error {
	mux.Handle(http.MethodGet, pattern_Redirector_RedirectURL_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		annotatedContext, err := runtime.AnnotateContext(ctx, mux, req, "/redirectorpb.Redirector/RedirectURL", runtime.WithHTTPPathPattern("/{short_url}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_Redirector_RedirectURL_0(annotatedContext, inboundMarshaler, client, req, pathParams)
		annotatedContext = runtime.NewServerMetadataContext(annotatedContext, md)
		if err != nil {
			runtime.HTTPError(annotatedContext, mux, outboundMarshaler, w, req, err)
			return
		}
		forward_Redirector_RedirectURL_0(annotatedContext, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)
	})
	return nil
}

var (
	pattern_Redirector_RedirectURL_0 = runtime.MustPattern(runtime.NewPattern(1, []int{1, 0, 4, 1, 5, 0}, []string{"short_url"}, ""))
)

var (
	forward_Redirector_RedirectURL_0 = runtime.ForwardResponseMessage
)
