// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: redirector.proto

package redirectorpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RedirectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectRequest) Reset() {
	*x = RedirectRequest{}
	mi := &file_redirector_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectRequest) ProtoMessage() {}

func (x *RedirectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_redirector_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectRequest.ProtoReflect.Descriptor instead.
func (*RedirectRequest) Descriptor() ([]byte, []int) {
	return file_redirector_proto_rawDescGZIP(), []int{0}
}

func (x *RedirectRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RedirectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceUrl     string                 `protobuf:"bytes,1,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectResponse) Reset() {
	*x = RedirectResponse{}
	mi := &file_redirector_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectResponse) ProtoMessage() {}

func (x *RedirectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_redirector_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectResponse.ProtoReflect.Descriptor instead.
func (*RedirectResponse) Descriptor() ([]byte, []int) {
	return file_redirector_proto_rawDescGZIP(), []int{1}
}

func (x *RedirectResponse) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

var File_redirector_proto protoreflect.FileDescriptor

const file_redirector_proto_rawDesc = "" +
	"\n" +
	"\x10redirector.proto\x12\fredirectorpb\x1a\x1cgoogle/api/annotations.proto\".\n" +
	"\x0fRedirectRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"1\n" +
	"\x10RedirectResponse\x12\x1d\n" +
	"\n" +
	"source_url\x18\x01 \x01(\tR\tsourceUrl2p\n" +
	"\n" +
	"Redirector\x12b\n" +
	"\vRedirectURL\x12\x1d.redirectorpb.RedirectRequest\x1a\x1e.redirectorpb.RedirectResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/{short_url}BEZCgithub.com/onemoreslacker/shortener/internal/api/proto/redirectorpbb\x06proto3"

var (
	file_redirector_proto_rawDescOnce sync.Once
	file_redirector_proto_rawDescData []byte
)

func file_redirector_proto_rawDescGZIP() []byte {
	file_redirector_proto_rawDescOnce.Do(func() {
		file_redirector_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_redirector_proto_rawDesc), len(file_redirector_proto_rawDesc)))
	})
	return file_redirector_proto_rawDescData
}

var file_redirector_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_redirector_proto_goTypes = []any{
	(*RedirectRequest)(nil),  // 0: redirectorpb.RedirectRequest
	(*RedirectResponse)(nil), // 1: redirectorpb.RedirectResponse
}
var file_redirector_proto_depIdxs = []int32{
	0, // 0: redirectorpb.Redirector.RedirectURL:input_type -> redirectorpb.RedirectRequest
	1, // 1: redirectorpb.Redirector.RedirectURL:output_type -> redirectorpb.RedirectResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_redirector_proto_init() }
func file_redirector_proto_init() {
	if File_redirector_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_redirector_proto_rawDesc), len(file_redirector_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_redirector_proto_goTypes,
		DependencyIndexes: file_redirector_proto_depIdxs,
		MessageInfos:      file_redirector_proto_msgTypes,
	}.Build()
	File_redirector_proto = out.File
	file_redirector_proto_goTypes = nil
	file_redirector_proto_depIdxs = nil
}
