{
 "title": "URL Shortener Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Redirector Bad Response",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total_redirector{code=~\"4..|5..\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shortener Bad Responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total_shortener{code=\"400\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redirector Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_redirector_sum[$__rate_interval])) / sum(rate(http_request_duration_redirector_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shortener Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_shortener_sum[$__rate_interval])) / sum(rate(http_request_duration_shortener_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}